export const Items1 = [
    {
        name:"hung3",
        date:"1/1/2023",
        cost:"20$"
    },
    {
        name:"huưeqe",
        date:"1/1/2023",
        cost:"20$"
    },
    {
        name:"hutry",
        date:"1/1/2023",
        cost:"20$"
    },
    {
        name:"htrỷy",
        date:"1/1/2023",
        cost:"20$"
    },
    {
        name:"hufghf",
        date:"1/1/2023",
        cost:"20$"
    },
    {
        name:"huvbcbvcg",
        date:"1/1/2023",
        cost:"20$"
    }
];
export const Items2 = [
    {
        name:"hung3",
        date:"1/1/2023",
        cost:"20$"
    },
    {
        name:"huưeqe",
        date:"1/1/2023",
        cost:"20$"
    },
    {
        name:"hutry",
        date:"1/1/2023",
        cost:"20$"
    },
    {
        name:"htrỷy",
        date:"1/1/2023",
        cost:"20$"
    },
    {
        name:"hufghf",
        date:"1/1/2023",
        cost:"20$"
    },
    {
        name:"huvbcbvcg",
        date:"1/1/2023",
        cost:"20$"
    }
];
export const Items3 = [
    {
        name:"hung3",
        date:"1/1/2023",
        cost:"20$"
    },
    {
        name:"huưeqe",
        date:"1/1/2023",
        cost:"20$"
    },
    {
        name:"hutry",
        date:"1/1/2023",
        cost:"20$"
    },
    {
        name:"htrỷy",
        date:"1/1/2023",
        cost:"20$"
    },
    {
        name:"hufghf",
        date:"1/1/2023",
        cost:"20$"
    },
    {
        name:"huvbcbvcg",
        date:"1/1/2023",
        cost:"20$"
    }
];